# Generated by Django 5.2.9 on 2026-03-22 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('expense', '0001_initial'),
        ('income', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_quantity', models.IntegerField(default=0, verbose_name='product quantity before')),
                ('new_quantity', models.IntegerField(default=0, verbose_name='Product quantity after')),
                ('quantity_change', models.IntegerField(default=0, verbose_name='quantity difference')),
                ('reason', models.CharField(choices=[('INITIAL', 'Initial'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return')], max_length=20, verbose_name='Stock movement reason')),
                ('comment', models.CharField(blank=True, max_length=250, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Change date')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product id')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.purchase')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='income.sale')),
            ],
        ),
    ]
