# Generated by Django 5.2.9 on 2026-03-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invetory_record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='product_id',
            new_name='product',
        ),
    ]
