# Generated by Django 5.2.9 on 2026-03-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invetory_record', '0002_rename_product_id_stockmovement_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='quantity',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='new_quantity',
            field=models.IntegerField(default=0, verbose_name='Product quantity after'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='old_quantity',
            field=models.IntegerField(default=0, verbose_name='product quantity before'),
        ),
    ]
