# Generated by Django 5.2.9 on 2026-03-10 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        ('income', '0005_alter_income_comment'),
        ('invetory_record', '0003_remove_stockmovement_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.purchase'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_change',
            field=models.IntegerField(default=0, verbose_name='quantity difference'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='income.sale'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return')], max_length=20, verbose_name='Stock movement reason'),
        ),
    ]
