# Generated by Django 5.2.9 on 2025-12-27 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Product name')),
                ('description', models.CharField(max_length=250, verbose_name='Product description')),
                ('quantity', models.IntegerField(default=0, verbose_name='Product quantity')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product cost price')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product sale price')),
                ('active', models.BooleanField(default=True, verbose_name='Product still saling')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Preoduct created date')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
