# Generated by Django 5.2.9 on 2025-12-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_user_id_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Product description'),
        ),
    ]
