# Generated by Django 5.2.9 on 2026-03-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='purchse_type',
            new_name='expense_type',
        ),
    ]
