# Generated by Django 5.2.9 on 2026-03-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_purchse_type_expense_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='comment',
            field=models.CharField(blank=True, default=''),
        ),
    ]
