# Generated by Django 5.2.9 on 2026-03-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='comment',
            field=models.CharField(blank=True),
        ),
    ]
