# Generated by Django 5.2.9 on 2026-01-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='sale',
            new_name='sale_id',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='sale',
            new_name='sale_id',
        ),
    ]
