# Generated by Django 5.2.9 on 2026-01-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_rename_sale_income_sale_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='sale_id',
            new_name='sale',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='sale_id',
            new_name='sale',
        ),
    ]
