# Generated by Django 5.2.9 on 2026-01-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_rename_sale_id_income_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='comment',
            field=models.CharField(blank=True, null=True),
        ),
    ]
