# Generated by Django 5.2.9 on 2026-03-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_income_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='comment',
            field=models.CharField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
